[package]
name = "bench"
version = "0.1.0"
authors = ["Jaemin Yoo <jmin.yoo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.1"
